/*
 * Phone.com API
 * This is a Phone.com api Swagger definition
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apisupport@phone.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.CallNotifications;
import io.swagger.client.model.Voicemail;

/**
 * CreateExtensionParams
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-04-03T15:39:58.948Z")
public class CreateExtensionParams {
  @SerializedName("voicemail")
  private Voicemail voicemail = null;

  @SerializedName("call_notifications")
  private CallNotifications callNotifications = null;

  @SerializedName("caller_id")
  private String callerId = null;

  @SerializedName("usage_type")
  private String usageType = null;

  @SerializedName("allows_call_waiting")
  private Boolean allowsCallWaiting = null;

  @SerializedName("extension")
  private Integer extension = null;

  @SerializedName("include_in_directory")
  private Boolean includeInDirectory = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("full_name")
  private String fullName = null;

  @SerializedName("timezone")
  private String timezone = null;

  @SerializedName("name_greeting")
  private Object nameGreeting = null;

  @SerializedName("local_area_code")
  private Integer localAreaCode = null;

  @SerializedName("enable_outbound_calls")
  private Boolean enableOutboundCalls = null;

  @SerializedName("enable_call_waiting")
  private Boolean enableCallWaiting = null;

  public CreateExtensionParams voicemail(Voicemail voicemail) {
    this.voicemail = voicemail;
    return this;
  }

   /**
   * Voicemail object
   * @return voicemail
  **/
  @ApiModelProperty(example = "null", value = "Voicemail object")
  public Voicemail getVoicemail() {
    return voicemail;
  }

  public void setVoicemail(Voicemail voicemail) {
    this.voicemail = voicemail;
  }

  public CreateExtensionParams callNotifications(CallNotifications callNotifications) {
    this.callNotifications = callNotifications;
    return this;
  }

   /**
   * Call Notifications object
   * @return callNotifications
  **/
  @ApiModelProperty(example = "null", value = "Call Notifications object")
  public CallNotifications getCallNotifications() {
    return callNotifications;
  }

  public void setCallNotifications(CallNotifications callNotifications) {
    this.callNotifications = callNotifications;
  }

  public CreateExtensionParams callerId(String callerId) {
    this.callerId = callerId;
    return this;
  }

   /**
   * Caller ID
   * @return callerId
  **/
  @ApiModelProperty(example = "null", value = "Caller ID")
  public String getCallerId() {
    return callerId;
  }

  public void setCallerId(String callerId) {
    this.callerId = callerId;
  }

  public CreateExtensionParams usageType(String usageType) {
    this.usageType = usageType;
    return this;
  }

   /**
   * Extension type
   * @return usageType
  **/
  @ApiModelProperty(example = "null", value = "Extension type")
  public String getUsageType() {
    return usageType;
  }

  public void setUsageType(String usageType) {
    this.usageType = usageType;
  }

  public CreateExtensionParams allowsCallWaiting(Boolean allowsCallWaiting) {
    this.allowsCallWaiting = allowsCallWaiting;
    return this;
  }

   /**
   * Allows call waiting
   * @return allowsCallWaiting
  **/
  @ApiModelProperty(example = "null", value = "Allows call waiting")
  public Boolean getAllowsCallWaiting() {
    return allowsCallWaiting;
  }

  public void setAllowsCallWaiting(Boolean allowsCallWaiting) {
    this.allowsCallWaiting = allowsCallWaiting;
  }

  public CreateExtensionParams extension(Integer extension) {
    this.extension = extension;
    return this;
  }

   /**
   * Extension number (auto-generated if empty)
   * @return extension
  **/
  @ApiModelProperty(example = "null", value = "Extension number (auto-generated if empty)")
  public Integer getExtension() {
    return extension;
  }

  public void setExtension(Integer extension) {
    this.extension = extension;
  }

  public CreateExtensionParams includeInDirectory(Boolean includeInDirectory) {
    this.includeInDirectory = includeInDirectory;
    return this;
  }

   /**
   * Include in dial-by-name directory
   * @return includeInDirectory
  **/
  @ApiModelProperty(example = "null", value = "Include in dial-by-name directory")
  public Boolean getIncludeInDirectory() {
    return includeInDirectory;
  }

  public void setIncludeInDirectory(Boolean includeInDirectory) {
    this.includeInDirectory = includeInDirectory;
  }

  public CreateExtensionParams name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Name (auto-generated if empty)
   * @return name
  **/
  @ApiModelProperty(example = "null", value = "Name (auto-generated if empty)")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public CreateExtensionParams fullName(String fullName) {
    this.fullName = fullName;
    return this;
  }

   /**
   * Contact name
   * @return fullName
  **/
  @ApiModelProperty(example = "null", value = "Contact name")
  public String getFullName() {
    return fullName;
  }

  public void setFullName(String fullName) {
    this.fullName = fullName;
  }

  public CreateExtensionParams timezone(String timezone) {
    this.timezone = timezone;
    return this;
  }

   /**
   * Timezone
   * @return timezone
  **/
  @ApiModelProperty(example = "null", value = "Timezone")
  public String getTimezone() {
    return timezone;
  }

  public void setTimezone(String timezone) {
    this.timezone = timezone;
  }

  public CreateExtensionParams nameGreeting(Object nameGreeting) {
    this.nameGreeting = nameGreeting;
    return this;
  }

   /**
   * Recording lookup object
   * @return nameGreeting
  **/
  @ApiModelProperty(example = "null", value = "Recording lookup object")
  public Object getNameGreeting() {
    return nameGreeting;
  }

  public void setNameGreeting(Object nameGreeting) {
    this.nameGreeting = nameGreeting;
  }

  public CreateExtensionParams localAreaCode(Integer localAreaCode) {
    this.localAreaCode = localAreaCode;
    return this;
  }

   /**
   * Local area code
   * @return localAreaCode
  **/
  @ApiModelProperty(example = "null", value = "Local area code")
  public Integer getLocalAreaCode() {
    return localAreaCode;
  }

  public void setLocalAreaCode(Integer localAreaCode) {
    this.localAreaCode = localAreaCode;
  }

  public CreateExtensionParams enableOutboundCalls(Boolean enableOutboundCalls) {
    this.enableOutboundCalls = enableOutboundCalls;
    return this;
  }

   /**
   * Enable outgoing calls
   * @return enableOutboundCalls
  **/
  @ApiModelProperty(example = "null", value = "Enable outgoing calls")
  public Boolean getEnableOutboundCalls() {
    return enableOutboundCalls;
  }

  public void setEnableOutboundCalls(Boolean enableOutboundCalls) {
    this.enableOutboundCalls = enableOutboundCalls;
  }

  public CreateExtensionParams enableCallWaiting(Boolean enableCallWaiting) {
    this.enableCallWaiting = enableCallWaiting;
    return this;
  }

   /**
   * Enable Call Waiting
   * @return enableCallWaiting
  **/
  @ApiModelProperty(example = "null", value = "Enable Call Waiting")
  public Boolean getEnableCallWaiting() {
    return enableCallWaiting;
  }

  public void setEnableCallWaiting(Boolean enableCallWaiting) {
    this.enableCallWaiting = enableCallWaiting;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreateExtensionParams createExtensionParams = (CreateExtensionParams) o;
    return Objects.equals(this.voicemail, createExtensionParams.voicemail) &&
        Objects.equals(this.callNotifications, createExtensionParams.callNotifications) &&
        Objects.equals(this.callerId, createExtensionParams.callerId) &&
        Objects.equals(this.usageType, createExtensionParams.usageType) &&
        Objects.equals(this.allowsCallWaiting, createExtensionParams.allowsCallWaiting) &&
        Objects.equals(this.extension, createExtensionParams.extension) &&
        Objects.equals(this.includeInDirectory, createExtensionParams.includeInDirectory) &&
        Objects.equals(this.name, createExtensionParams.name) &&
        Objects.equals(this.fullName, createExtensionParams.fullName) &&
        Objects.equals(this.timezone, createExtensionParams.timezone) &&
        Objects.equals(this.nameGreeting, createExtensionParams.nameGreeting) &&
        Objects.equals(this.localAreaCode, createExtensionParams.localAreaCode) &&
        Objects.equals(this.enableOutboundCalls, createExtensionParams.enableOutboundCalls) &&
        Objects.equals(this.enableCallWaiting, createExtensionParams.enableCallWaiting);
  }

  @Override
  public int hashCode() {
    return Objects.hash(voicemail, callNotifications, callerId, usageType, allowsCallWaiting, extension, includeInDirectory, name, fullName, timezone, nameGreeting, localAreaCode, enableOutboundCalls, enableCallWaiting);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreateExtensionParams {\n");
    
    sb.append("    voicemail: ").append(toIndentedString(voicemail)).append("\n");
    sb.append("    callNotifications: ").append(toIndentedString(callNotifications)).append("\n");
    sb.append("    callerId: ").append(toIndentedString(callerId)).append("\n");
    sb.append("    usageType: ").append(toIndentedString(usageType)).append("\n");
    sb.append("    allowsCallWaiting: ").append(toIndentedString(allowsCallWaiting)).append("\n");
    sb.append("    extension: ").append(toIndentedString(extension)).append("\n");
    sb.append("    includeInDirectory: ").append(toIndentedString(includeInDirectory)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    fullName: ").append(toIndentedString(fullName)).append("\n");
    sb.append("    timezone: ").append(toIndentedString(timezone)).append("\n");
    sb.append("    nameGreeting: ").append(toIndentedString(nameGreeting)).append("\n");
    sb.append("    localAreaCode: ").append(toIndentedString(localAreaCode)).append("\n");
    sb.append("    enableOutboundCalls: ").append(toIndentedString(enableOutboundCalls)).append("\n");
    sb.append("    enableCallWaiting: ").append(toIndentedString(enableCallWaiting)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

