/*
 * Phone.com API
 * This is a Phone.com api Swagger definition
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apisupport@phone.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.CallNotifications;
import io.swagger.client.model.CallerIdPhoneNumber;
import io.swagger.client.model.SmsForwardingParams;

/**
 * CreatePhoneNumberParams
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-04-03T15:39:58.948Z")
public class CreatePhoneNumberParams {
  @SerializedName("phone_number")
  private Object phoneNumber = null;

  @SerializedName("route")
  private Object route = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("block_incoming")
  private Boolean blockIncoming = null;

  @SerializedName("block_anonymous")
  private Boolean blockAnonymous = null;

  @SerializedName("caller_id")
  private CallerIdPhoneNumber callerId = null;

  @SerializedName("sms_forwarding")
  private SmsForwardingParams smsForwarding = null;

  @SerializedName("call_notifications")
  private CallNotifications callNotifications = null;

  public CreatePhoneNumberParams phoneNumber(Object phoneNumber) {
    this.phoneNumber = phoneNumber;
    return this;
  }

   /**
   * Phone number
   * @return phoneNumber
  **/
  @ApiModelProperty(example = "null", value = "Phone number")
  public Object getPhoneNumber() {
    return phoneNumber;
  }

  public void setPhoneNumber(Object phoneNumber) {
    this.phoneNumber = phoneNumber;
  }

  public CreatePhoneNumberParams route(Object route) {
    this.route = route;
    return this;
  }

   /**
   * Route lookup object
   * @return route
  **/
  @ApiModelProperty(example = "null", value = "Route lookup object")
  public Object getRoute() {
    return route;
  }

  public void setRoute(Object route) {
    this.route = route;
  }

  public CreatePhoneNumberParams name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Phone Name
   * @return name
  **/
  @ApiModelProperty(example = "null", value = "Phone Name")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public CreatePhoneNumberParams blockIncoming(Boolean blockIncoming) {
    this.blockIncoming = blockIncoming;
    return this;
  }

   /**
   * Block incoming calls
   * @return blockIncoming
  **/
  @ApiModelProperty(example = "null", value = "Block incoming calls")
  public Boolean getBlockIncoming() {
    return blockIncoming;
  }

  public void setBlockIncoming(Boolean blockIncoming) {
    this.blockIncoming = blockIncoming;
  }

  public CreatePhoneNumberParams blockAnonymous(Boolean blockAnonymous) {
    this.blockAnonymous = blockAnonymous;
    return this;
  }

   /**
   * Block anonymous calls
   * @return blockAnonymous
  **/
  @ApiModelProperty(example = "null", value = "Block anonymous calls")
  public Boolean getBlockAnonymous() {
    return blockAnonymous;
  }

  public void setBlockAnonymous(Boolean blockAnonymous) {
    this.blockAnonymous = blockAnonymous;
  }

  public CreatePhoneNumberParams callerId(CallerIdPhoneNumber callerId) {
    this.callerId = callerId;
    return this;
  }

   /**
   * Caller ID object
   * @return callerId
  **/
  @ApiModelProperty(example = "null", value = "Caller ID object")
  public CallerIdPhoneNumber getCallerId() {
    return callerId;
  }

  public void setCallerId(CallerIdPhoneNumber callerId) {
    this.callerId = callerId;
  }

  public CreatePhoneNumberParams smsForwarding(SmsForwardingParams smsForwarding) {
    this.smsForwarding = smsForwarding;
    return this;
  }

   /**
   * SMS Forwarding Object, or NULL
   * @return smsForwarding
  **/
  @ApiModelProperty(example = "null", value = "SMS Forwarding Object, or NULL")
  public SmsForwardingParams getSmsForwarding() {
    return smsForwarding;
  }

  public void setSmsForwarding(SmsForwardingParams smsForwarding) {
    this.smsForwarding = smsForwarding;
  }

  public CreatePhoneNumberParams callNotifications(CallNotifications callNotifications) {
    this.callNotifications = callNotifications;
    return this;
  }

   /**
   * Call Notifications object
   * @return callNotifications
  **/
  @ApiModelProperty(example = "null", value = "Call Notifications object")
  public CallNotifications getCallNotifications() {
    return callNotifications;
  }

  public void setCallNotifications(CallNotifications callNotifications) {
    this.callNotifications = callNotifications;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreatePhoneNumberParams createPhoneNumberParams = (CreatePhoneNumberParams) o;
    return Objects.equals(this.phoneNumber, createPhoneNumberParams.phoneNumber) &&
        Objects.equals(this.route, createPhoneNumberParams.route) &&
        Objects.equals(this.name, createPhoneNumberParams.name) &&
        Objects.equals(this.blockIncoming, createPhoneNumberParams.blockIncoming) &&
        Objects.equals(this.blockAnonymous, createPhoneNumberParams.blockAnonymous) &&
        Objects.equals(this.callerId, createPhoneNumberParams.callerId) &&
        Objects.equals(this.smsForwarding, createPhoneNumberParams.smsForwarding) &&
        Objects.equals(this.callNotifications, createPhoneNumberParams.callNotifications);
  }

  @Override
  public int hashCode() {
    return Objects.hash(phoneNumber, route, name, blockIncoming, blockAnonymous, callerId, smsForwarding, callNotifications);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreatePhoneNumberParams {\n");
    
    sb.append("    phoneNumber: ").append(toIndentedString(phoneNumber)).append("\n");
    sb.append("    route: ").append(toIndentedString(route)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    blockIncoming: ").append(toIndentedString(blockIncoming)).append("\n");
    sb.append("    blockAnonymous: ").append(toIndentedString(blockAnonymous)).append("\n");
    sb.append("    callerId: ").append(toIndentedString(callerId)).append("\n");
    sb.append("    smsForwarding: ").append(toIndentedString(smsForwarding)).append("\n");
    sb.append("    callNotifications: ").append(toIndentedString(callNotifications)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

