/*
 * Phone.com API
 * This is a Phone.com api Swagger definition
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apisupport@phone.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.AccountFull;
import io.swagger.client.model.ListAccountsFull;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for AccountsApi
 */
@Ignore
public class AccountsApiTest {

    private final AccountsApi api = new AccountsApi();

    
    /**
     * Retrieve details of an individual account
     *
     * This service shows the details of an individual account. See Accounts for more info on the properties.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getAccountTest() throws ApiException {
        Integer accountId = 1315091;
        AccountFull response = api.getAccount(accountId);

        // TODO: test validations
    }
    
    /**
     * Get a list of accounts visible to the authenticated user or client
     *
     * This service lists the accounts accessible to the authenticated client. In most cases, there will only be one such account. See Accounts for more info on the properties.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void listAccountsTest() throws ApiException {
        List<String> filtersId = null;
        String sortId = null;
        Integer limit = null;
        Integer offset = null;
        String fields = null;
        ListAccountsFull response = api.listAccounts(filtersId, sortId, limit, offset, fields);

        // TODO: test validations
    }
    
}
