/*
 * Phone.com API
 * This is a Phone.com api Swagger definition
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apisupport@phone.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.ListAvailableNumbersFull;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for AvailablenumbersApi
 */
@Ignore
public class AvailablenumbersApiTest {

    private final AvailablenumbersApi api = new AvailablenumbersApi();

    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void listAvailablePhoneNumbersTest() throws ApiException {
        List<String> filtersPhoneNumber = null;
        List<String> filtersCountryCode = null;
        List<String> filtersNpa = null;
        List<String> filtersNxx = null;
        List<String> filtersXxxx = null;
        List<String> filtersCity = null;
        List<String> filtersProvince = null;
        List<String> filtersCountry = null;
        List<String> filtersPrice = null;
        List<String> filtersCategory = null;
        String sortInternal = null;
        String sortPrice = null;
        String sortPhoneNumber = null;
        Integer limit = null;
        Integer offset = null;
        String fields = null;
        ListAvailableNumbersFull response = api.listAvailablePhoneNumbers(filtersPhoneNumber, filtersCountryCode, filtersNpa, filtersNxx, filtersXxxx, filtersCity, filtersProvince, filtersCountry, filtersPrice, filtersCategory, sortInternal, sortPrice, sortPhoneNumber, limit, offset, fields);

        // TODO: test validations
    }
    
}
