/*
 * Phone.com API
 * This is a Phone.com api Swagger definition
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apisupport@phone.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.ListCallerIdsFull;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for CalleridsApi
 */
@Ignore
public class CalleridsApiTest {

    private final CalleridsApi api = new CalleridsApi();

    
    /**
     * Show the Caller ID options a given extension can use
     *
     * Get Caller ID
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getCallerIdsTest() throws ApiException {
        Integer accountId = 1315091;
        Integer extensionId = 1764590;
        List<String> filtersNumber = null;
        List<String> filtersName = null;
        String sortNumber = null;
        String sortName = null;
        Integer limit = null;
        Integer offset = null;
        String fields = null;
        ListCallerIdsFull response = api.getCallerIds(accountId, extensionId, filtersNumber, filtersName, sortNumber, sortName, limit, offset, fields);

        // TODO: test validations
    }
    
}
