/*
 * Phone.com API
 * This is a Phone.com api Swagger definition
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apisupport@phone.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.ExpressServiceCodeFull;
import io.swagger.client.model.ListExpressServiceCodesFull;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ExpressservicecodesApi
 */
@Ignore
public class ExpressservicecodesApiTest {

    private final ExpressservicecodesApi api = new ExpressservicecodesApi();

    
    /**
     * Show details of an account Express Service Code
     *
     * This service shows the details of an Account Express Service Code.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getAccountExpressSrvCodeTest() throws ApiException {
        Integer accountId = 1315091;
        Integer codeId = 323446;
        ExpressServiceCodeFull response = api.getAccountExpressSrvCode(accountId, codeId);

        // TODO: test validations
    }
    
    /**
     * Get the Express Service Code associated with your account in list format
     *
     * See Express Service Codes for more detail.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void listAccountExpressSrvCodesTest() throws ApiException {
        Integer accountId = 1315091;
        List<String> filtersId = null;
        ListExpressServiceCodesFull response = api.listAccountExpressSrvCodes(accountId, filtersId);

        // TODO: test validations
    }
    
}
