/*
 * Phone.com API
 * This is a Phone.com api Swagger definition
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apisupport@phone.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.CreateMenuParams;
import io.swagger.client.model.DeleteMenu;
import io.swagger.client.model.ListMenusFull;
import io.swagger.client.model.MenuFull;
import io.swagger.client.model.ReplaceMenuParams;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for MenusApi
 */
@Ignore
public class MenusApiTest {

    private final MenusApi api = new MenusApi();

    
    /**
     * Create an individual menu
     *
     * This service creates an individual menu. See Account Menus for more info on the properties.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createAccountMenuTest() throws ApiException {
        Integer accountId = 1315091;
        CreateMenuParams data = null;
        MenuFull response = api.createAccountMenu(accountId, data);

        // TODO: test validations
    }
    
    /**
     * Delete an individual menu
     *
     * This service shows the details of an individual menu.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteAccountMenuTest() throws ApiException {
        Integer accountId = 1315091;
        Integer menuId = null;
        DeleteMenu response = api.deleteAccountMenu(accountId, menuId);

        // TODO: test validations
    }
    
    /**
     * Show details of an individual menu
     *
     * This service shows the details of an individual Menu.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getAccountMenuTest() throws ApiException {
        Integer accountId = 1315091;
        Integer menuId = 88294;
        MenuFull response = api.getAccountMenu(accountId, menuId);

        // TODO: test validations
    }
    
    /**
     * Get a list of menus for an account
     *
     * See Account Menus for more info on the properties.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void listAccountMenusTest() throws ApiException {
        Integer accountId = 1315091;
        List<String> filtersId = null;
        List<String> filtersName = null;
        String sortId = null;
        String sortName = null;
        Integer limit = null;
        Integer offset = null;
        String fields = null;
        ListMenusFull response = api.listAccountMenus(accountId, filtersId, filtersName, sortId, sortName, limit, offset, fields);

        // TODO: test validations
    }
    
    /**
     * Replace an individual menu
     *
     * This service replaces the details of an individual Menu.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void replaceAccountMenuTest() throws ApiException {
        Integer accountId = 1315091;
        Integer menuId = null;
        ReplaceMenuParams data = null;
        MenuFull response = api.replaceAccountMenu(accountId, menuId, data);

        // TODO: test validations
    }
    
}
