/*
 * Phone.com API
 * This is a Phone.com api Swagger definition
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apisupport@phone.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.ListPhoneNumbersRegionsFull;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for NumberregionsApi
 */
@Ignore
public class NumberregionsApiTest {

    private final NumberregionsApi api = new NumberregionsApi();

    
    /**
     * 
     *
     * This service lists the quantities of available phone numbers by region.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void listAvailablePhoneNumberRegionsTest() throws ApiException {
        List<String> filtersCountryCode = null;
        List<String> filtersNpa = null;
        List<String> filtersNxx = null;
        List<String> filtersIsTollFree = null;
        List<String> filtersCity = null;
        List<String> filtersProvincePostalCode = null;
        List<String> filtersCountryPostalCode = null;
        String sortCountryCode = null;
        String sortNpa = null;
        String sortNxx = null;
        String sortIsTollFree = null;
        String sortCity = null;
        String sortProvincePostalCode = null;
        String sortCountryPostalCode = null;
        Integer limit = null;
        Integer offset = null;
        String fields = null;
        List<String> groupBy = null;
        ListPhoneNumbersRegionsFull response = api.listAvailablePhoneNumberRegions(filtersCountryCode, filtersNpa, filtersNxx, filtersIsTollFree, filtersCity, filtersProvincePostalCode, filtersCountryPostalCode, sortCountryCode, sortNpa, sortNxx, sortIsTollFree, sortCity, sortProvincePostalCode, sortCountryPostalCode, limit, offset, fields, groupBy);

        // TODO: test validations
    }
    
}
