/*
 * Phone.com API
 * This is a Phone.com api Swagger definition
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apisupport@phone.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.CreatePhoneNumberParams;
import io.swagger.client.model.ListPhoneNumbersFull;
import io.swagger.client.model.PhoneNumberFull;
import io.swagger.client.model.ReplacePhoneNumberParams;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for PhonenumbersApi
 */
@Ignore
public class PhonenumbersApiTest {

    private final PhonenumbersApi api = new PhonenumbersApi();

    
    /**
     * Add a phone number to an account
     *
     * See Intro to Account Phone Numbers for more info on the properties to use.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createAccountPhoneNumberTest() throws ApiException {
        Integer accountId = 1315091;
        CreatePhoneNumberParams data = null;
        PhoneNumberFull response = api.createAccountPhoneNumber(accountId, data);

        // TODO: test validations
    }
    
    /**
     * Show details of an individual phone number
     *
     * See Intro to Account Phone Numbers for more info on the properties.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getAccountPhoneNumberTest() throws ApiException {
        Integer accountId = 1315091;
        Integer numberId = 2116986;
        PhoneNumberFull response = api.getAccountPhoneNumber(accountId, numberId);

        // TODO: test validations
    }
    
    /**
     * Get a list of phone numbers registered to an account
     *
     * See Intro to Account Phone Numbers for more info on the properties.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void listAccountPhoneNumbersTest() throws ApiException {
        Integer accountId = 1315091;
        List<String> filtersId = null;
        List<String> filtersName = null;
        List<String> filtersPhoneNumber = null;
        String sortId = null;
        String sortName = null;
        String sortPhoneNumber = null;
        Integer limit = null;
        Integer offset = null;
        String fields = null;
        ListPhoneNumbersFull response = api.listAccountPhoneNumbers(accountId, filtersId, filtersName, filtersPhoneNumber, sortId, sortName, sortPhoneNumber, limit, offset, fields);

        // TODO: test validations
    }
    
    /**
     * Update the settings for an existing phone number on your account
     *
     * See Intro to Account Phone Numbers for more info on the properties.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void replaceAccountPhoneNumberTest() throws ApiException {
        Integer accountId = 1315091;
        Integer numberId = null;
        ReplacePhoneNumberParams data = null;
        PhoneNumberFull response = api.replaceAccountPhoneNumber(accountId, numberId, data);

        // TODO: test validations
    }
    
}
