/*
 * Phone.com API
 * This is a Phone.com api Swagger definition
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apisupport@phone.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.CreateQueueParams;
import io.swagger.client.model.DeleteQueue;
import io.swagger.client.model.ListQueuesFull;
import io.swagger.client.model.QueueFull;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for QueuesApi
 */
@Ignore
public class QueuesApiTest {

    private final QueuesApi api = new QueuesApi();

    
    /**
     * Create a queue
     *
     * For more on the input fields, see Account Queues.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createAccountQueueTest() throws ApiException {
        Integer accountId = 1315091;
        CreateQueueParams data = null;
        QueueFull response = api.createAccountQueue(accountId, data);

        // TODO: test validations
    }
    
    /**
     * Delete a queue
     *
     * This service a queue from the account. For more information on queue properties, see Account Queues.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteAccountQueueTest() throws ApiException {
        Integer accountId = 1315091;
        Integer queueId = null;
        DeleteQueue response = api.deleteAccountQueue(accountId, queueId);

        // TODO: test validations
    }
    
    /**
     * Show details of an individual queue
     *
     * This service shows the details of an individual queue. For more on the input fields, see Account Queues.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getAccountQueueTest() throws ApiException {
        Integer accountId = 1315091;
        Integer queueId = null;
        QueueFull response = api.getAccountQueue(accountId, queueId);

        // TODO: test validations
    }
    
    /**
     * Get a list of queues for an account
     *
     * The List Queues service lists all the queues belong to the account. See Account Queues for more info on the properties.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void listAccountQueuesTest() throws ApiException {
        Integer accountId = 1315091;
        List<String> filtersId = null;
        List<String> filtersName = null;
        String sortId = null;
        String sortName = null;
        Integer limit = null;
        Integer offset = null;
        String fields = null;
        ListQueuesFull response = api.listAccountQueues(accountId, filtersId, filtersName, sortId, sortName, limit, offset, fields);

        // TODO: test validations
    }
    
    /**
     * Replace a queue
     *
     * The Replace Queue service replaces the parameters of a queue. For more on the input fields, see Account Queues.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void replaceAccountQueueTest() throws ApiException {
        Integer accountId = 1315091;
        Integer queueId = null;
        CreateQueueParams data = null;
        QueueFull response = api.replaceAccountQueue(accountId, queueId, data);

        // TODO: test validations
    }
    
}
