/*
 * Phone.com API
 * This is a Phone.com api Swagger definition
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apisupport@phone.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.ListSchedulesFull;
import io.swagger.client.model.ScheduleFull;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for SchedulesApi
 */
@Ignore
public class SchedulesApiTest {

    private final SchedulesApi api = new SchedulesApi();

    
    /**
     * Show details of an individual schedule
     *
     * This service shows the details of an individual schedule.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getAccountScheduleTest() throws ApiException {
        Integer accountId = 1315091;
        Integer scheduleId = null;
        ScheduleFull response = api.getAccountSchedule(accountId, scheduleId);

        // TODO: test validations
    }
    
    /**
     * Get a list of schedules for an account
     *
     * See Intro to Schedules for more info on the properties.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void listAccountSchedulesTest() throws ApiException {
        Integer accountId = 1315091;
        List<String> filtersId = null;
        List<String> filtersName = null;
        String sortId = null;
        String sortName = null;
        Integer limit = null;
        Integer offset = null;
        String fields = null;
        ListSchedulesFull response = api.listAccountSchedules(accountId, filtersId, filtersName, sortId, sortName, limit, offset, fields);

        // TODO: test validations
    }
    
}
