/*
 * Phone.com API
 * This is a Phone.com api Swagger definition
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apisupport@phone.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.CreateSmsParams;
import io.swagger.client.model.ListSmsFull;
import io.swagger.client.model.SmsFull;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for SmsApi
 */
@Ignore
public class SmsApiTest {

    private final SmsApi api = new SmsApi();

    
    /**
     * Send a SMS to one or a group of recipients
     *
     * For more on the input fields, see Intro to SMS.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createAccountSmsTest() throws ApiException {
        Integer accountId = 1315091;
        CreateSmsParams data = null;
        SmsFull response = api.createAccountSms(accountId, data);

        // TODO: test validations
    }
    
    /**
     * Show details of an individual SMS
     *
     * This service shows the details of an individual sms. See Intro to SMS for more info on the properties.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getAccountSmsTest() throws ApiException {
        Integer accountId = 1315091;
        Integer smsId = null;
        SmsFull response = api.getAccountSms(accountId, smsId);

        // TODO: test validations
    }
    
    /**
     * Get a list of SMS messages for an account
     *
     * See Intro to SMS for more info on the properties.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void listAccountSmsTest() throws ApiException {
        Integer accountId = 1315091;
        List<String> filtersId = null;
        String filtersDirection = null;
        String filtersFrom = null;
        String sortId = null;
        String sortCreatedAt = null;
        Integer limit = null;
        Integer offset = null;
        String fields = null;
        ListSmsFull response = api.listAccountSms(accountId, filtersId, filtersDirection, filtersFrom, sortId, sortCreatedAt, limit, offset, fields);

        // TODO: test validations
    }
    
}
