/*
 * Phone.com API
 * This is a Phone.com api Swagger definition
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apisupport@phone.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.AccountFull;
import io.swagger.client.model.CreateSubaccountParams;
import io.swagger.client.model.ListAccountsFull;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for SubaccountsApi
 */
@Ignore
public class SubaccountsApiTest {

    private final SubaccountsApi api = new SubaccountsApi();

    
    /**
     * Add a subaccount for the authenticated user or client
     *
     * This service shows the details of an individual Subaccount.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createAccountSubaccountTest() throws ApiException {
        Integer accountId = 1315091;
        CreateSubaccountParams data = null;
        AccountFull response = api.createAccountSubaccount(accountId, data);

        // TODO: test validations
    }
    
    /**
     * Get a list of subaccounts for the authenticated user or client
     *
     * This service lists the Subaccount of the authenticated client. In most cases, there will not be any.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void listAccountSubaccountsTest() throws ApiException {
        Integer accountId = 1315091;
        List<String> filtersId = null;
        String sortId = null;
        Integer limit = null;
        Integer offset = null;
        String fields = null;
        ListAccountsFull response = api.listAccountSubaccounts(accountId, filtersId, sortId, limit, offset, fields);

        // TODO: test validations
    }
    
}
