/*
 * Phone.com API
 * This is a Phone.com api Swagger definition
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apisupport@phone.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.CreateTrunkParams;
import io.swagger.client.model.DeleteTrunk;
import io.swagger.client.model.ListTrunksFull;
import io.swagger.client.model.TrunkFull;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for TrunksApi
 */
@Ignore
public class TrunksApiTest {

    private final TrunksApi api = new TrunksApi();

    
    /**
     * Add a trunk record with SIP information
     *
     * For more on the input fields, see Account Trunks.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createAccountTrunkTest() throws ApiException {
        Integer accountId = 1315091;
        CreateTrunkParams data = null;
        TrunkFull response = api.createAccountTrunk(accountId, data);

        // TODO: test validations
    }
    
    /**
     * Delete a trunk from account
     *
     * This service deletes a trunk from the account. For more on the properties of trunks, see Account Trunks.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteAccountTrunkTest() throws ApiException {
        Integer accountId = 1315091;
        Integer trunkId = null;
        DeleteTrunk response = api.deleteAccountTrunk(accountId, trunkId);

        // TODO: test validations
    }
    
    /**
     * Show details of an individual trunk
     *
     * This service shows the details of an individual Trunk.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getAccountTrunkTest() throws ApiException {
        Integer accountId = 1315091;
        Integer trunkId = null;
        TrunkFull response = api.getAccountTrunk(accountId, trunkId);

        // TODO: test validations
    }
    
    /**
     * Get a list of trunks for an account
     *
     * See Account Trunks for more info on the properties.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void listAccountTrunksTest() throws ApiException {
        Integer accountId = 1315091;
        List<String> filtersId = null;
        List<String> filtersName = null;
        String sortId = null;
        String sortName = null;
        Integer limit = null;
        Integer offset = null;
        String fields = null;
        ListTrunksFull response = api.listAccountTrunks(accountId, filtersId, filtersName, sortId, sortName, limit, offset, fields);

        // TODO: test validations
    }
    
    /**
     * Replace parameters in a trunk
     *
     * For more on the input fields, see Account Trunks.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void replaceAccountTrunkTest() throws ApiException {
        Integer accountId = 1315091;
        Integer trunkId = null;
        CreateTrunkParams data = null;
        TrunkFull response = api.replaceAccountTrunk(accountId, trunkId, data);

        // TODO: test validations
    }
    
}
